DROP DATABASE IF EXISTS api_db;
DROP USER IF EXISTS api_db_user;
CREATE DATABASE api_db;
CREATE USER api_db_user WITH PASSWORD 'Interforaewg098!';
GRANT ALL PRIVILEGES ON DATABASE api_db TO api_db_user;